### ISSUE TITLE
Change variant insert to variant upsert in variant.sql.ts

### ISSUE THREAD

**Issue by shanil-sasikumar** [netspective-studios/PgDCP#7]
When I try to insert the same value to the variant tables, a constraint violation error is throwing. I fixed it like the following

```
IF NOT EXISTS(SELECT 1 from etc_text WHERE name = 'XXXXXXXX') THEN 
          INSERT INTO etc_text (name, description, value)
          VALUES ('XXXXXXXX', 'XXXXXXX', 'XXXXXXXX');    
END IF;
```

**Comment by shah** [comment]
Variants should no longer be used and we should only have type-safe tables so I'm closing this.
